GOOGLE_GENAI_USE_VERTEXAI: "true"
GOOGLE_CLOUD_PROJECT: "voiceagent-483614"
GOOGLE_CLOUD_LOCATION: "us-central1"
USE_DB: "TRUE"
USE_LOCAL_DB: "FALSE"
USE_CLOUD_SQL: "TRUE"
DB_HOST: "/cloudsql/voiceagent-483614:us-central1:voiceagent-db"
CLOUD_SQL_CONNECTION_NAME: "voiceagent-483614:us-central1:voiceagent-db"
CORS_ORIGINS: "http://localhost:9002,https://pre-registration.nxtwave.in,https://va-staging-483614.web.app,https://voiceagent-prod-483614.web.app,https://nxtgig.tech"
